theme: jekyll-theme-cayman
# remote_theme: lewismiddleton/cayman-dark
name: Akash WebSpace
description: Minimal Portfolio
title: Akash WebSpace
show_downloads: false
favicon: /favicon.ico
use_logo: true
logo: /assets/logo.png
show_feedback: true
feedback_email: akash@foxraving.com

# inserts github link in top nav bar (recommended)
github_button_location_top_navbar: false

# inserts github link below page title
github_button_location_below_title: false

# inserts github link at bottom of page (least visible)
github_button_location_page_bottom: false

google_analytics: G-XQPQCD736L
